### PR TITLE
[Fixes #260] Make space trimming consistent for all task arguments

### LINKED ISSUE #216: Rake removes trailing whitespaces from parameters when task is being executed from command line.
Having a simple rake task:
  ```ruby
    task :ws, [:str] => :environment do |t, args|
      puts args.str.inspect
    end
  ```
I get following results when run this task in command line:
  ```bash
    $ rake ws[' ']
    nil
    
    $ rake ws['    ']
    nil
    
    $ rake ws['    1']
    "    1"
    
    $ rake ws['    1    ']
    "    1"
    
    $ rake 'ws[ ]'
    nil
    
    $ rake 'ws[    ]'
    nil
    
    $ rake 'ws[    1]'
    "    1"
    
    $ rake 'ws[    1    ]'
    "    1"
  ```
While when the task is being invoked in rails console everything works as expected:
  ```ruby
    2.3.3 :258 > Rake::Task['ws'].invoke(' ')
    " "
    2.3.3 :259 > Rake::Task['ws'].reenable
    2.3.3 :260 > Rake::Task['ws'].invoke('    ')
    "    "
    2.3.3 :261 > Rake::Task['ws'].reenable
    2.3.3 :262 > Rake::Task['ws'].invoke('    1')
    "    1"
    2.3.3 :263 > Rake::Task['ws'].reenable
    2.3.3 :264 > Rake::Task['ws'].invoke('    1    ')
    "    1    "
  ```
Again, it is definitely not the OS who is responsible for that trimming, since it shouldn't trim anything between quote marks. And besides it can be easily tested this way:
  ```ruby
    task :ws, [:str] => :environment do |t, args|
      puts args.str.inspect
      puts ARGV[1].inspect
    end
  ```
then in command line:
  ```bash
    $ rake 'ws[  1  ]' '  2  '
    "  1"
    "  2  "
  ```
Rake version 12.0.0

### LINKED ISSUE #260: Task argument trimming is not completely consistent
Given a task that just inspect args...

```
$ bundle exec rake "inspect_args[  one  ,  two  ,  three  ]"
"  one"
"two"
"three"
```

It almost works, the only trimming not working is the one for the leading whitespaces of the first argument.

### PR DESCRIPTION
**Pull request by grzuy**
Fixes #260

Given a task that just inspect task arguments...

Current rake behavior
```
$ bundle exec rake "inspect_args[  one  ,  two  ,  three  ]"
"  one"
"two"
"three"
```

With this PR changes
```
$ bundle exec rake "inspect_args[  one  ,  two  ,  three  ]"
"one"
"two"
"three"
```

### CODE REVIEW

**Comment by grzuy** [comment]
@hsbt @yuki24 Any feedback on this one? :-)

File: test/test_rake_task_argument_parsing.rb [hunk 1]
```diff
@@ -32,8 +32,8 @@ def test_two_arguments
     assert_equal ["one", "two"], args
   end
 
-  def test_can_handle_spaces_between_args
-    name, args = @app.parse_task_string("name[one, two,\tthree , \tfour]")
+  def test_can_handle_spaces_between_all_args
+    name, args = @app.parse_task_string("name[ one , two ,\tthree , \tfour ]")
```
Comment (yuki24) [inline test/test_rake_task_argument_parsing.rb]: Keep the existing test and add a new test as this is technically a new feature. Also, make sure it doesn't strip out whitespaces in a string literal:

```sh
rake name[one,two,three]     # => should be interpreted as `rake name[one,two,three]`
rake name[ one , two, three] # => should be interpreted as `rake name[one,two,three]`

rake name["one two",three]   # => should be interpreted as `rake name["one two",three]`
rake name[ "one two", three] # => should be interpreted as `rake name["one two",three]`
```

Comment (grzuy) [reply test/test_rake_task_argument_parsing.rb]: Thanks for the feedback.

Added original test back.
Regarding your second comment, i think there's already a test case below testing that whitespaces embedded in arguments are not strip out. Let me know if that covers it.

Added new commit, let me know if you prefer amend.

**Comment by hsbt** [comment]
Thanks!
